void run_program()
catch exception from std::get<InitState2>

